[package]
distribution = "2201.9.0"
org = "ballerinax"
name = "aws.dynamodb"
version = "2.3.1"
authors = ["Ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-aws.dynamodb"
keywords = ["Communication/Email", "Cost/Free", "Vendor/Google"]
icon = "icon.png"
license = ["Apache-2.0"]

[build-options]
observabilityIncluded = true
